// Auto-generated by scripts/extract-review-content.mjs
// Re-run the script to regenerate. Do not edit manually.

export interface ReviewSub {
  name: string;
  file: string;
}

export interface ReviewTopic {
  name: string;
  file: string;
  subs: ReviewSub[];
}

export interface ReviewCategory {
  title: string;
  icon: string;
  topics: ReviewTopic[];
}

export const REVIEW_TOPICS: ReviewCategory[] = [
  {
    "title": "1. Core Java",
    "icon": "🔷",
    "topics": [
      {
        "name": "OOP",
        "file": "oop",
        "subs": [
          {
            "name": "Encapsulation",
            "file": "encapsulation"
          },
          {
            "name": "Inheritance",
            "file": "inheritance"
          },
          {
            "name": "Polymorphism",
            "file": "polymorphism"
          },
          {
            "name": "Abstraction",
            "file": "abstraction"
          },
          {
            "name": "Interface vs Abstract Class",
            "file": "interface-vs-abstract-class"
          }
        ]
      },
      {
        "name": "JVM Internals",
        "file": "jvm-internals",
        "subs": [
          {
            "name": "Heap",
            "file": "heap"
          },
          {
            "name": "Stack",
            "file": "stack"
          },
          {
            "name": "Metaspace",
            "file": "metaspace"
          },
          {
            "name": "Class Loading",
            "file": "class-loading"
          },
          {
            "name": "Garbage Collection",
            "file": "garbage-collection"
          },
          {
            "name": "Memory Leaks",
            "file": "memory-leaks"
          }
        ]
      },
      {
        "name": "Collections",
        "file": "collections",
        "subs": [
          {
            "name": "ArrayList vs LinkedList",
            "file": "arraylist-vs-linkedlist"
          },
          {
            "name": "HashMap Internals",
            "file": "hashmap-internals"
          },
          {
            "name": "ConcurrentHashMap",
            "file": "concurrenthashmap"
          },
          {
            "name": "TreeMap / LinkedHashMap",
            "file": "treemap-linkedhashmap"
          }
        ]
      },
      {
        "name": "Exception Handling",
        "file": "exception-handling",
        "subs": [
          {
            "name": "Checked vs Unchecked",
            "file": "checked-vs-unchecked"
          },
          {
            "name": "try-with-resources",
            "file": "try-with-resources"
          },
          {
            "name": "Custom Exceptions",
            "file": "custom-exceptions"
          }
        ]
      },
      {
        "name": "Java I/O",
        "file": "java-i-o",
        "subs": [
          {
            "name": "Blocking I/O (java.io)",
            "file": "blocking-i-o-java-io"
          },
          {
            "name": "NIO (Non-Blocking)",
            "file": "nio-non-blocking"
          },
          {
            "name": "NIO.2 Path & Files",
            "file": "nio-2-path-files"
          },
          {
            "name": "So sánh các mô hình I/O",
            "file": "so-sanh-cac-mo-hinh-i-o"
          }
        ]
      },
      {
        "name": "Performance Tuning",
        "file": "performance-tuning",
        "subs": [
          {
            "name": "Công cụ Profiling (jstack/jmap/jcmd)",
            "file": "cong-cu-profiling-jstack-jmap-jcmd"
          },
          {
            "name": "Phân tích Heap Dump",
            "file": "phan-tich-heap-dump"
          },
          {
            "name": "Phân tích Thread Dump",
            "file": "phan-tich-thread-dump"
          },
          {
            "name": "JVM Flags Cheatsheet",
            "file": "jvm-flags-cheatsheet"
          }
        ]
      }
    ]
  },
  {
    "title": "2. Concurrency",
    "icon": "⚡",
    "topics": [
      {
        "name": "Thread Lifecycle",
        "file": "thread-lifecycle",
        "subs": []
      },
      {
        "name": "Synchronization",
        "file": "synchronization",
        "subs": [
          {
            "name": "synchronized keyword",
            "file": "synchronized-keyword"
          },
          {
            "name": "wait / notify",
            "file": "wait-notify"
          },
          {
            "name": "ReentrantLock",
            "file": "reentrantlock"
          }
        ]
      },
      {
        "name": "Volatile",
        "file": "volatile",
        "subs": []
      },
      {
        "name": "Atomic Classes",
        "file": "atomic-classes",
        "subs": [
          {
            "name": "AtomicInteger",
            "file": "atomicinteger"
          },
          {
            "name": "CAS (Compare-And-Swap)",
            "file": "cas-compare-and-swap"
          }
        ]
      },
      {
        "name": "Thread Pool",
        "file": "thread-pool",
        "subs": [
          {
            "name": "ExecutorService",
            "file": "executorservice"
          },
          {
            "name": "CompletableFuture",
            "file": "completablefuture"
          }
        ]
      },
      {
        "name": "Deadlock",
        "file": "deadlock",
        "subs": []
      },
      {
        "name": "Race Condition",
        "file": "race-condition",
        "subs": []
      },
      {
        "name": "Starvation",
        "file": "starvation",
        "subs": []
      },
      {
        "name": "Java Memory Model",
        "file": "java-memory-model",
        "subs": [
          {
            "name": "happens-before",
            "file": "happens-before"
          },
          {
            "name": "visibility / ordering",
            "file": "visibility-ordering"
          }
        ]
      }
    ]
  },
  {
    "title": "3. Spring Ecosystem",
    "icon": "🍃",
    "topics": [
      {
        "name": "Spring Core",
        "file": "spring-core",
        "subs": [
          {
            "name": "IoC Container",
            "file": "ioc-container"
          },
          {
            "name": "Dependency Injection",
            "file": "dependency-injection"
          },
          {
            "name": "Bean Lifecycle",
            "file": "bean-lifecycle"
          },
          {
            "name": "Bean Scope",
            "file": "bean-scope"
          }
        ]
      },
      {
        "name": "Spring Boot",
        "file": "spring-boot",
        "subs": [
          {
            "name": "Auto Configuration",
            "file": "auto-configuration"
          },
          {
            "name": "Profiles",
            "file": "profiles"
          },
          {
            "name": "Actuator",
            "file": "actuator"
          }
        ]
      },
      {
        "name": "Spring MVC",
        "file": "spring-mvc",
        "subs": [
          {
            "name": "Request Flow",
            "file": "request-flow"
          },
          {
            "name": "Filters vs Interceptors",
            "file": "filters-vs-interceptors"
          },
          {
            "name": "Exception Handling (@ControllerAdvice)",
            "file": "exception-handling-controlleradvice"
          }
        ]
      },
      {
        "name": "Spring Security",
        "file": "spring-security",
        "subs": [
          {
            "name": "JWT",
            "file": "jwt"
          },
          {
            "name": "OAuth2",
            "file": "oauth2"
          },
          {
            "name": "Authentication vs Authorization",
            "file": "authentication-vs-authorization"
          }
        ]
      },
      {
        "name": "Spring AOP",
        "file": "spring-aop",
        "subs": [
          {
            "name": "Proxy Mechanism",
            "file": "proxy-mechanism"
          },
          {
            "name": "Aspect / Pointcut / Advice",
            "file": "aspect-pointcut-advice"
          },
          {
            "name": "Cross-Cutting Concerns",
            "file": "cross-cutting-concerns"
          }
        ]
      }
    ]
  },
  {
    "title": "4. Database",
    "icon": "🗄️",
    "topics": [
      {
        "name": "SQL",
        "file": "sql",
        "subs": [
          {
            "name": "Joins",
            "file": "joins"
          },
          {
            "name": "Window Functions",
            "file": "window-functions"
          },
          {
            "name": "GROUP BY / HAVING",
            "file": "group-by-having"
          }
        ]
      },
      {
        "name": "Indexing",
        "file": "indexing",
        "subs": [
          {
            "name": "B-Tree Index",
            "file": "b-tree-index"
          },
          {
            "name": "Composite Index",
            "file": "composite-index"
          },
          {
            "name": "Covering Index",
            "file": "covering-index"
          }
        ]
      },
      {
        "name": "Transactions",
        "file": "transactions",
        "subs": [
          {
            "name": "ACID",
            "file": "acid"
          },
          {
            "name": "Isolation Levels",
            "file": "isolation-levels"
          },
          {
            "name": "Locking",
            "file": "locking"
          }
        ]
      },
      {
        "name": "JPA / Hibernate",
        "file": "jpa-hibernate",
        "subs": [
          {
            "name": "Entity Lifecycle",
            "file": "entity-lifecycle"
          },
          {
            "name": "Lazy Loading",
            "file": "lazy-loading"
          },
          {
            "name": "N+1 Problem",
            "file": "n-1-problem"
          },
          {
            "name": "Optimistic / Pessimistic Locking",
            "file": "optimistic-pessimistic-locking"
          }
        ]
      },
      {
        "name": "NoSQL",
        "file": "nosql",
        "subs": [
          {
            "name": "Redis",
            "file": "redis"
          },
          {
            "name": "MongoDB",
            "file": "mongodb"
          },
          {
            "name": "When to Use NoSQL",
            "file": "when-to-use-nosql"
          }
        ]
      },
      {
        "name": "MyBatis",
        "file": "mybatis",
        "subs": [
          {
            "name": "Mapper & XML Mapping",
            "file": "mapper-xml-mapping"
          },
          {
            "name": "Dynamic SQL",
            "file": "dynamic-sql"
          },
          {
            "name": "ResultMap",
            "file": "resultmap"
          },
          {
            "name": "MyBatis vs JPA",
            "file": "mybatis-vs-jpa"
          }
        ]
      },
      {
        "name": "MySQL Deep Dive",
        "file": "mysql-deep-dive",
        "subs": [
          {
            "name": "InnoDB & MVCC",
            "file": "innodb-mvcc"
          },
          {
            "name": "Đọc EXPLAIN Plan",
            "file": "oc-explain-plan"
          },
          {
            "name": "Slow Query Log",
            "file": "slow-query-log"
          },
          {
            "name": "Connection Pool (HikariCP)",
            "file": "connection-pool-hikaricp"
          }
        ]
      }
    ]
  },
  {
    "title": "5. Microservices",
    "icon": "🔗",
    "topics": [
      {
        "name": "Service Discovery",
        "file": "service-discovery",
        "subs": [
          {
            "name": "Eureka / Consul",
            "file": "eureka-consul"
          }
        ]
      },
      {
        "name": "API Gateway",
        "file": "api-gateway",
        "subs": [
          {
            "name": "Routing & Rate Limiting",
            "file": "routing-rate-limiting"
          }
        ]
      },
      {
        "name": "Circuit Breaker",
        "file": "circuit-breaker",
        "subs": [
          {
            "name": "Resilience4j",
            "file": "resilience4j"
          },
          {
            "name": "States: CLOSED → OPEN → HALF_OPEN",
            "file": "states-closed-open-half-open"
          }
        ]
      },
      {
        "name": "Service Communication",
        "file": "service-communication",
        "subs": [
          {
            "name": "REST vs gRPC",
            "file": "rest-vs-grpc"
          },
          {
            "name": "Feign Client",
            "file": "feign-client"
          }
        ]
      },
      {
        "name": "Saga Pattern",
        "file": "saga-pattern",
        "subs": [
          {
            "name": "Choreography",
            "file": "choreography"
          },
          {
            "name": "Orchestration",
            "file": "orchestration"
          }
        ]
      }
    ]
  },
  {
    "title": "6. Messaging",
    "icon": "📨",
    "topics": [
      {
        "name": "Kafka",
        "file": "kafka",
        "subs": [
          {
            "name": "Topic / Partition / Offset",
            "file": "topic-partition-offset"
          },
          {
            "name": "Producer & Consumer",
            "file": "producer-consumer"
          },
          {
            "name": "Consumer Group",
            "file": "consumer-group"
          },
          {
            "name": "Ordering Guarantees",
            "file": "ordering-guarantees"
          }
        ]
      },
      {
        "name": "RabbitMQ",
        "file": "rabbitmq",
        "subs": [
          {
            "name": "Exchange / Queue / Binding",
            "file": "exchange-queue-binding"
          },
          {
            "name": "Routing Keys",
            "file": "routing-keys"
          }
        ]
      },
      {
        "name": "Common Concepts",
        "file": "",
        "subs": [
          {
            "name": "Dead Letter Queue (DLQ)",
            "file": "dead-letter-queue-dlq"
          },
          {
            "name": "Idempotency / Deduplication",
            "file": "idempotency-deduplication"
          },
          {
            "name": "Retry Strategies",
            "file": "retry-strategies"
          },
          {
            "name": "At-Least-Once vs Exactly-Once",
            "file": "at-least-once-vs-exactly-once"
          }
        ]
      }
    ]
  },
  {
    "title": "7. System Design",
    "icon": "🏗️",
    "topics": [
      {
        "name": "Scalability",
        "file": "scalability",
        "subs": [
          {
            "name": "Horizontal vs Vertical",
            "file": "horizontal-vs-vertical"
          },
          {
            "name": "Stateless Services",
            "file": "stateless-services"
          }
        ]
      },
      {
        "name": "Load Balancing",
        "file": "load-balancing",
        "subs": [
          {
            "name": "Algorithms",
            "file": "algorithms"
          },
          {
            "name": "Consistent Hashing",
            "file": "consistent-hashing"
          }
        ]
      },
      {
        "name": "Caching",
        "file": "caching",
        "subs": [
          {
            "name": "Cache-Aside",
            "file": "cache-aside"
          },
          {
            "name": "Write-Through / Write-Behind",
            "file": "write-through-write-behind"
          },
          {
            "name": "Eviction Policies",
            "file": "eviction-policies"
          }
        ]
      },
      {
        "name": "Database Scaling",
        "file": "database-scaling",
        "subs": [
          {
            "name": "Read Replica",
            "file": "read-replica"
          },
          {
            "name": "Sharding",
            "file": "sharding"
          },
          {
            "name": "CQRS",
            "file": "cqrs"
          }
        ]
      },
      {
        "name": "Distributed Lock",
        "file": "distributed-lock",
        "subs": [
          {
            "name": "Redis SETNX / Redlock",
            "file": "redis-setnx-redlock"
          }
        ]
      },
      {
        "name": "Rate Limiting",
        "file": "rate-limiting",
        "subs": [
          {
            "name": "Token Bucket",
            "file": "token-bucket"
          },
          {
            "name": "Sliding Window",
            "file": "sliding-window"
          }
        ]
      },
      {
        "name": "CAP Theorem",
        "file": "cap-theorem",
        "subs": []
      },
      {
        "name": "Consistency Patterns",
        "file": "consistency-patterns",
        "subs": [
          {
            "name": "Eventual Consistency",
            "file": "eventual-consistency"
          },
          {
            "name": "Strong Consistency",
            "file": "strong-consistency"
          }
        ]
      },
      {
        "name": "High Concurrency",
        "file": "high-concurrency",
        "subs": [
          {
            "name": "Sizing Thread Pool",
            "file": "sizing-thread-pool"
          },
          {
            "name": "Tuning Connection Pool",
            "file": "tuning-connection-pool"
          },
          {
            "name": "Bulkhead & Isolation",
            "file": "bulkhead-isolation"
          },
          {
            "name": "Capacity Planning",
            "file": "capacity-planning"
          }
        ]
      }
    ]
  },
  {
    "title": "8. Cloud & DevOps",
    "icon": "☁️",
    "topics": [
      {
        "name": "Docker",
        "file": "docker",
        "subs": [
          {
            "name": "Image / Container / Layer",
            "file": "image-container-layer"
          },
          {
            "name": "Dockerfile Best Practices",
            "file": "dockerfile-best-practices"
          },
          {
            "name": "Networking & Volumes",
            "file": "networking-volumes"
          }
        ]
      },
      {
        "name": "Kubernetes",
        "file": "kubernetes",
        "subs": [
          {
            "name": "Pod / Deployment / Service",
            "file": "pod-deployment-service"
          },
          {
            "name": "ConfigMap & Secret",
            "file": "configmap-secret"
          },
          {
            "name": "HPA & Rolling Update",
            "file": "hpa-rolling-update"
          }
        ]
      },
      {
        "name": "CI/CD",
        "file": "ci-cd",
        "subs": [
          {
            "name": "Pipeline Stages",
            "file": "pipeline-stages"
          },
          {
            "name": "Blue-Green & Canary Deploy",
            "file": "blue-green-canary-deploy"
          }
        ]
      },
      {
        "name": "Monitoring",
        "file": "monitoring",
        "subs": [
          {
            "name": "Prometheus & Grafana",
            "file": "prometheus-grafana"
          },
          {
            "name": "Distributed Tracing",
            "file": "distributed-tracing"
          },
          {
            "name": "Structured Logging",
            "file": "structured-logging"
          }
        ]
      }
    ]
  },
  {
    "title": "9. Testing",
    "icon": "🧪",
    "topics": [
      {
        "name": "Unit Test",
        "file": "unit-test",
        "subs": [
          {
            "name": "JUnit 5 Annotations",
            "file": "junit-5-annotations"
          },
          {
            "name": "Parameterized Tests",
            "file": "parameterized-tests"
          }
        ]
      },
      {
        "name": "Mocking",
        "file": "mocking",
        "subs": [
          {
            "name": "Mockito (Mock / Spy / Captor)",
            "file": "mockito-mock-spy-captor"
          },
          {
            "name": "When to Mock",
            "file": "when-to-mock"
          }
        ]
      },
      {
        "name": "Integration Test",
        "file": "integration-test",
        "subs": [
          {
            "name": "@SpringBootTest",
            "file": "springboottest"
          },
          {
            "name": "TestContainers",
            "file": "testcontainers"
          }
        ]
      },
      {
        "name": "Contract Testing",
        "file": "contract-testing",
        "subs": [
          {
            "name": "Pact",
            "file": "pact"
          }
        ]
      },
      {
        "name": "Performance Testing",
        "file": "performance-testing",
        "subs": [
          {
            "name": "JMeter / Gatling / k6",
            "file": "jmeter-gatling-k6"
          }
        ]
      }
    ]
  },
  {
    "title": "10. Design Patterns",
    "icon": "🎨",
    "topics": [
      {
        "name": "Creational",
        "file": "creational",
        "subs": [
          {
            "name": "Singleton",
            "file": "singleton"
          },
          {
            "name": "Factory Method",
            "file": "factory-method"
          },
          {
            "name": "Builder",
            "file": "builder"
          },
          {
            "name": "Prototype",
            "file": "prototype"
          }
        ]
      },
      {
        "name": "Structural",
        "file": "structural",
        "subs": [
          {
            "name": "Adapter",
            "file": "adapter"
          },
          {
            "name": "Decorator",
            "file": "decorator"
          },
          {
            "name": "Facade",
            "file": "facade"
          },
          {
            "name": "Proxy",
            "file": "proxy"
          }
        ]
      },
      {
        "name": "Behavioral",
        "file": "behavioral",
        "subs": [
          {
            "name": "Strategy",
            "file": "strategy"
          },
          {
            "name": "Observer",
            "file": "observer"
          },
          {
            "name": "Template Method",
            "file": "template-method"
          },
          {
            "name": "Command",
            "file": "command"
          },
          {
            "name": "Chain of Responsibility",
            "file": "chain-of-responsibility"
          }
        ]
      }
    ]
  },
  {
    "title": "11. Linux & Deployment",
    "icon": "🐧",
    "topics": [
      {
        "name": "File & Process",
        "file": "file-process",
        "subs": []
      },
      {
        "name": "Network & Logs",
        "file": "network-logs",
        "subs": []
      },
      {
        "name": "Service Deployment",
        "file": "service-deployment",
        "subs": []
      }
    ]
  }
];
