// Auto-generated by scripts/extract-review-content.mjs
// Re-run the script to regenerate. Do not edit manually.

export interface ReviewSub {
  name: string;
  file: string;
}

export interface ReviewTopic {
  name: string;
  file: string;
  subs: ReviewSub[];
}

export interface ReviewCategory {
  title: string;
  icon: string;
  topics: ReviewTopic[];
}

export const REVIEW_TOPICS: ReviewCategory[] = [
  {
    "title": "1. Core Java",
    "icon": "🔷",
    "topics": [
      {
        "name": "OOP",
        "file": "oop",
        "subs": [
          {
            "name": "Encapsulation",
            "file": "encapsulation"
          },
          {
            "name": "Inheritance",
            "file": "inheritance"
          },
          {
            "name": "Polymorphism",
            "file": "polymorphism"
          },
          {
            "name": "Abstraction",
            "file": "abstraction"
          },
          {
            "name": "Interface vs Abstract Class",
            "file": "interface-vs-abstract-class"
          }
        ]
      },
      {
        "name": "JVM Internals",
        "file": "jvm-internals",
        "subs": [
          {
            "name": "Heap",
            "file": "heap"
          },
          {
            "name": "Stack",
            "file": "stack"
          },
          {
            "name": "Metaspace",
            "file": "metaspace"
          },
          {
            "name": "Class Loading",
            "file": "class-loading"
          },
          {
            "name": "Garbage Collection",
            "file": "garbage-collection"
          },
          {
            "name": "Memory Leaks",
            "file": "memory-leaks"
          }
        ]
      },
      {
        "name": "Collections",
        "file": "collections",
        "subs": [
          {
            "name": "ArrayList vs LinkedList",
            "file": "arraylist-vs-linkedlist"
          },
          {
            "name": "HashMap Internals",
            "file": "hashmap-internals"
          },
          {
            "name": "ConcurrentHashMap",
            "file": "concurrenthashmap"
          },
          {
            "name": "TreeMap / LinkedHashMap",
            "file": "treemap-linkedhashmap"
          }
        ]
      },
      {
        "name": "Exception Handling",
        "file": "exception-handling",
        "subs": [
          {
            "name": "Checked vs Unchecked",
            "file": "checked-vs-unchecked"
          },
          {
            "name": "try-with-resources",
            "file": "try-with-resources"
          },
          {
            "name": "Custom Exceptions",
            "file": "custom-exceptions"
          }
        ]
      },
      {
        "name": "Java I/O",
        "file": "java-i-o",
        "subs": [
          {
            "name": "Blocking I/O (java.io)",
            "file": "blocking-i-o-java-io"
          },
          {
            "name": "NIO (Non-Blocking)",
            "file": "nio-non-blocking"
          },
          {
            "name": "NIO.2 Path & Files",
            "file": "nio-2-path-files"
          },
          {
            "name": "So sánh các mô hình I/O",
            "file": "so-sanh-cac-mo-hinh-i-o"
          }
        ]
      },
      {
        "name": "Performance Tuning",
        "file": "performance-tuning",
        "subs": [
          {
            "name": "Công cụ Profiling (jstack/jmap/jcmd)",
            "file": "cong-cu-profiling-jstack-jmap-jcmd"
          },
          {
            "name": "Phân tích Heap Dump",
            "file": "phan-tich-heap-dump"
          },
          {
            "name": "Phân tích Thread Dump",
            "file": "phan-tich-thread-dump"
          },
          {
            "name": "JVM Flags Cheatsheet",
            "file": "jvm-flags-cheatsheet"
          }
        ]
      }
    ]
  },
  {
    "title": "2. Java Versions",
    "icon": "☕",
    "topics": [
      {
        "name": "Version History Overview",
        "file": "java-version-history",
        "subs": []
      },
      {
        "name": "Java 7 & 8 (Lambda, Stream, Optional)",
        "file": "java-7-8",
        "subs": []
      },
      {
        "name": "Java 9–11 (Modules, var, HTTP Client)",
        "file": "java-9-11",
        "subs": []
      },
      {
        "name": "Java 12–16 (Records, Text Blocks, Patterns)",
        "file": "java-12-16",
        "subs": []
      },
      {
        "name": "Java 17 LTS (Sealed Classes)",
        "file": "java-17",
        "subs": []
      },
      {
        "name": "Java 21 LTS (Virtual Threads)",
        "file": "java-21",
        "subs": []
      },
      {
        "name": "Java 22–25 (Gatherers, Structured Concurrency)",
        "file": "java-22-25",
        "subs": []
      }
    ]
  },
  {
    "title": "3. Kotlin",
    "icon": "🟣",
    "topics": [
      {
        "name": "Kotlin Cơ Bản",
        "file": "kotlin-basics",
        "subs": [
          {
            "name": "Data Class",
            "file": "kotlin-data-class"
          },
          {
            "name": "Null Safety",
            "file": "kotlin-null-safety"
          },
          {
            "name": "Sealed Class",
            "file": "kotlin-sealed-class"
          },
          {
            "name": "Object & Companion",
            "file": "kotlin-object-companion"
          },
          {
            "name": "Kotlin vs Java",
            "file": "kotlin-vs-java"
          }
        ]
      },
      {
        "name": "Coroutines",
        "file": "kotlin-coroutines",
        "subs": [
          {
            "name": "Coroutines Cơ Bản",
            "file": "kotlin-coroutines-basics"
          },
          {
            "name": "Exception & Cancellation",
            "file": "kotlin-coroutines-advanced"
          },
          {
            "name": "Dispatchers",
            "file": "kotlin-dispatcher"
          },
          {
            "name": "Flow",
            "file": "kotlin-flow"
          }
        ]
      },
      {
        "name": "Kotlin Features",
        "file": "kotlin-features",
        "subs": [
          {
            "name": "Scope Functions",
            "file": "kotlin-scope-functions"
          },
          {
            "name": "Extension Functions",
            "file": "kotlin-extension-functions"
          },
          {
            "name": "Higher-Order Functions",
            "file": "kotlin-higher-order-functions"
          },
          {
            "name": "Delegation",
            "file": "kotlin-delegation"
          }
        ]
      },
      {
        "name": "Collections & DSL",
        "file": "kotlin-collections-dsl",
        "subs": [
          {
            "name": "Collections & Sequences",
            "file": "kotlin-collections"
          }
        ]
      }
    ]
  },
  {
    "title": "4. Python",
    "icon": "🐍",
    "topics": [
      {
        "name": "Python Cơ Bản",
        "file": "python-basics",
        "subs": [
          {
            "name": "Data Types",
            "file": "python-data-types"
          },
          {
            "name": "Comprehensions",
            "file": "python-comprehensions"
          },
          {
            "name": "Type Hints",
            "file": "python-type-hints"
          },
          {
            "name": "OOP",
            "file": "python-oop"
          }
        ]
      },
      {
        "name": "Advanced Python",
        "file": "python-advanced",
        "subs": [
          {
            "name": "Decorators",
            "file": "python-decorators"
          },
          {
            "name": "Generators",
            "file": "python-generators"
          },
          {
            "name": "Context Managers",
            "file": "python-context-managers"
          },
          {
            "name": "Functional Programming",
            "file": "python-functional"
          }
        ]
      },
      {
        "name": "Python Internals",
        "file": "python-internals-overview",
        "subs": [
          {
            "name": "GIL",
            "file": "python-gil"
          },
          {
            "name": "Memory Model",
            "file": "python-memory-model"
          },
          {
            "name": "Metaclass & ABC",
            "file": "python-metaclass"
          },
          {
            "name": "CPython & Bytecode",
            "file": "python-internals"
          }
        ]
      },
      {
        "name": "Async & Web",
        "file": "python-async-web",
        "subs": [
          {
            "name": "async/await & asyncio",
            "file": "python-async-await"
          },
          {
            "name": "FastAPI",
            "file": "python-fastapi"
          }
        ]
      }
    ]
  },
  {
    "title": "5. ReactJS",
    "icon": "⚛️",
    "topics": [
      {
        "name": "React Hooks",
        "file": "react-hooks",
        "subs": [
          {
            "name": "useState & useReducer",
            "file": "react-usestate-usereducer"
          },
          {
            "name": "useEffect & useLayoutEffect",
            "file": "react-useeffect"
          },
          {
            "name": "useMemo & useCallback",
            "file": "react-usememo-usecallback"
          },
          {
            "name": "useRef & forwardRef",
            "file": "react-useref"
          },
          {
            "name": "Custom Hooks",
            "file": "react-custom-hooks"
          }
        ]
      },
      {
        "name": "React Internals",
        "file": "react-internals",
        "subs": [
          {
            "name": "Virtual DOM",
            "file": "react-virtual-dom"
          },
          {
            "name": "Reconciliation & Fiber",
            "file": "react-reconciliation"
          }
        ]
      },
      {
        "name": "State Management",
        "file": "react-state",
        "subs": [
          {
            "name": "Context API",
            "file": "react-context"
          },
          {
            "name": "Redux & Redux Toolkit",
            "file": "react-redux"
          },
          {
            "name": "Zustand",
            "file": "react-zustand"
          }
        ]
      },
      {
        "name": "Patterns & Performance",
        "file": "react-patterns",
        "subs": [
          {
            "name": "Component Patterns",
            "file": "react-component-patterns"
          },
          {
            "name": "Performance Optimization",
            "file": "react-performance"
          },
          {
            "name": "Suspense & Error Boundary",
            "file": "react-suspense"
          },
          {
            "name": "React Router v6",
            "file": "react-router"
          }
        ]
      }
    ]
  },
  {
    "title": "6. Concurrency",
    "icon": "⚡",
    "topics": [
      {
        "name": "Thread Lifecycle",
        "file": "thread-lifecycle",
        "subs": []
      },
      {
        "name": "Synchronization",
        "file": "synchronization",
        "subs": [
          {
            "name": "synchronized keyword",
            "file": "synchronized-keyword"
          },
          {
            "name": "wait / notify",
            "file": "wait-notify"
          },
          {
            "name": "ReentrantLock",
            "file": "reentrantlock"
          }
        ]
      },
      {
        "name": "Volatile",
        "file": "volatile",
        "subs": []
      },
      {
        "name": "Atomic Classes",
        "file": "atomic-classes",
        "subs": [
          {
            "name": "AtomicInteger",
            "file": "atomicinteger"
          },
          {
            "name": "CAS (Compare-And-Swap)",
            "file": "cas-compare-and-swap"
          }
        ]
      },
      {
        "name": "Thread Pool",
        "file": "thread-pool",
        "subs": [
          {
            "name": "ExecutorService",
            "file": "executorservice"
          },
          {
            "name": "CompletableFuture",
            "file": "completablefuture"
          }
        ]
      },
      {
        "name": "Deadlock",
        "file": "deadlock",
        "subs": []
      },
      {
        "name": "Race Condition",
        "file": "race-condition",
        "subs": []
      },
      {
        "name": "Starvation",
        "file": "starvation",
        "subs": []
      },
      {
        "name": "Java Memory Model",
        "file": "java-memory-model",
        "subs": [
          {
            "name": "happens-before",
            "file": "happens-before"
          },
          {
            "name": "visibility / ordering",
            "file": "visibility-ordering"
          }
        ]
      }
    ]
  },
  {
    "title": "7. Spring Ecosystem",
    "icon": "🍃",
    "topics": [
      {
        "name": "Spring Core",
        "file": "spring-core",
        "subs": [
          {
            "name": "IoC Container",
            "file": "ioc-container"
          },
          {
            "name": "Dependency Injection",
            "file": "dependency-injection"
          },
          {
            "name": "Bean Lifecycle",
            "file": "bean-lifecycle"
          },
          {
            "name": "Bean Scope",
            "file": "bean-scope"
          }
        ]
      },
      {
        "name": "Spring Boot",
        "file": "spring-boot",
        "subs": [
          {
            "name": "Auto Configuration",
            "file": "auto-configuration"
          },
          {
            "name": "Profiles",
            "file": "profiles"
          },
          {
            "name": "Actuator",
            "file": "actuator"
          }
        ]
      },
      {
        "name": "Spring MVC",
        "file": "spring-mvc",
        "subs": [
          {
            "name": "Request Flow",
            "file": "request-flow"
          },
          {
            "name": "Filters vs Interceptors",
            "file": "filters-vs-interceptors"
          },
          {
            "name": "Exception Handling (@ControllerAdvice)",
            "file": "exception-handling-controlleradvice"
          }
        ]
      },
      {
        "name": "Spring Security",
        "file": "spring-security",
        "subs": [
          {
            "name": "JWT",
            "file": "jwt"
          },
          {
            "name": "OAuth2",
            "file": "oauth2"
          },
          {
            "name": "Authentication vs Authorization",
            "file": "authentication-vs-authorization"
          }
        ]
      },
      {
        "name": "Spring AOP",
        "file": "spring-aop",
        "subs": [
          {
            "name": "Proxy Mechanism",
            "file": "proxy-mechanism"
          },
          {
            "name": "Aspect / Pointcut / Advice",
            "file": "aspect-pointcut-advice"
          },
          {
            "name": "Cross-Cutting Concerns",
            "file": "cross-cutting-concerns"
          }
        ]
      }
    ]
  },
  {
    "title": "8. Quarkus",
    "icon": "⚡",
    "topics": [
      {
        "name": "Quarkus Cơ Bản",
        "file": "quarkus-basics",
        "subs": [
          {
            "name": "Quarkus Basics",
            "file": "quarkus-basics"
          },
          {
            "name": "CDI & Dependency Injection",
            "file": "quarkus-cdi"
          },
          {
            "name": "Configuration",
            "file": "quarkus-config"
          },
          {
            "name": "Quarkus vs Spring Boot",
            "file": "quarkus-vs-spring"
          }
        ]
      },
      {
        "name": "RESTEasy Reactive",
        "file": "quarkus-rest",
        "subs": [
          {
            "name": "RESTEasy Reactive",
            "file": "quarkus-rest"
          },
          {
            "name": "Mutiny (Uni & Multi)",
            "file": "quarkus-mutiny"
          }
        ]
      },
      {
        "name": "Persistence",
        "file": "quarkus-panache",
        "subs": [
          {
            "name": "Panache ORM",
            "file": "quarkus-panache"
          }
        ]
      },
      {
        "name": "Native & Performance",
        "file": "quarkus-native",
        "subs": [
          {
            "name": "GraalVM Native Image",
            "file": "quarkus-native"
          },
          {
            "name": "Testing",
            "file": "quarkus-testing"
          }
        ]
      }
    ]
  },
  {
    "title": "9. Design Patterns",
    "icon": "🎨",
    "topics": [
      {
        "name": "Creational",
        "file": "creational",
        "subs": [
          {
            "name": "Singleton",
            "file": "singleton"
          },
          {
            "name": "Factory Method",
            "file": "factory-method"
          },
          {
            "name": "Builder",
            "file": "builder"
          },
          {
            "name": "Prototype",
            "file": "prototype"
          }
        ]
      },
      {
        "name": "Structural",
        "file": "structural",
        "subs": [
          {
            "name": "Adapter",
            "file": "adapter"
          },
          {
            "name": "Decorator",
            "file": "decorator"
          },
          {
            "name": "Facade",
            "file": "facade"
          },
          {
            "name": "Proxy",
            "file": "proxy"
          }
        ]
      },
      {
        "name": "Behavioral",
        "file": "behavioral",
        "subs": [
          {
            "name": "Strategy",
            "file": "strategy"
          },
          {
            "name": "Observer",
            "file": "observer"
          },
          {
            "name": "Template Method",
            "file": "template-method"
          },
          {
            "name": "Command",
            "file": "command"
          },
          {
            "name": "Chain of Responsibility",
            "file": "chain-of-responsibility"
          }
        ]
      },
      {
        "name": "Architecture Patterns",
        "file": "ddd-basics",
        "subs": [
          {
            "name": "DDD Basics",
            "file": "ddd-basics"
          },
          {
            "name": "Hexagonal Architecture",
            "file": "hexagonal-architecture"
          }
        ]
      }
    ]
  },
  {
    "title": "10. Database",
    "icon": "🗄️",
    "topics": [
      {
        "name": "SQL",
        "file": "sql",
        "subs": [
          {
            "name": "Joins",
            "file": "joins"
          },
          {
            "name": "Window Functions",
            "file": "window-functions"
          },
          {
            "name": "GROUP BY / HAVING",
            "file": "group-by-having"
          }
        ]
      },
      {
        "name": "Indexing",
        "file": "indexing",
        "subs": [
          {
            "name": "B-Tree Index",
            "file": "b-tree-index"
          },
          {
            "name": "Composite Index",
            "file": "composite-index"
          },
          {
            "name": "Covering Index",
            "file": "covering-index"
          }
        ]
      },
      {
        "name": "Transactions",
        "file": "transactions",
        "subs": [
          {
            "name": "ACID",
            "file": "acid"
          },
          {
            "name": "Isolation Levels",
            "file": "isolation-levels"
          },
          {
            "name": "Locking",
            "file": "locking"
          }
        ]
      },
      {
        "name": "JPA / Hibernate",
        "file": "jpa-hibernate",
        "subs": [
          {
            "name": "Entity Lifecycle",
            "file": "entity-lifecycle"
          },
          {
            "name": "Lazy Loading",
            "file": "lazy-loading"
          },
          {
            "name": "N+1 Problem",
            "file": "n-1-problem"
          },
          {
            "name": "Optimistic / Pessimistic Locking",
            "file": "optimistic-pessimistic-locking"
          }
        ]
      },
      {
        "name": "NoSQL",
        "file": "nosql",
        "subs": [
          {
            "name": "Redis",
            "file": "redis"
          },
          {
            "name": "MongoDB",
            "file": "mongodb"
          },
          {
            "name": "When to Use NoSQL",
            "file": "when-to-use-nosql"
          }
        ]
      },
      {
        "name": "MyBatis",
        "file": "mybatis",
        "subs": [
          {
            "name": "Mapper & XML Mapping",
            "file": "mapper-xml-mapping"
          },
          {
            "name": "Dynamic SQL",
            "file": "dynamic-sql"
          },
          {
            "name": "ResultMap",
            "file": "resultmap"
          },
          {
            "name": "MyBatis vs JPA",
            "file": "mybatis-vs-jpa"
          }
        ]
      },
      {
        "name": "MySQL Deep Dive",
        "file": "mysql-deep-dive",
        "subs": [
          {
            "name": "InnoDB & MVCC",
            "file": "innodb-mvcc"
          },
          {
            "name": "Đọc EXPLAIN Plan",
            "file": "oc-explain-plan"
          },
          {
            "name": "Slow Query Log",
            "file": "slow-query-log"
          },
          {
            "name": "Connection Pool (HikariCP)",
            "file": "connection-pool-hikaricp"
          }
        ]
      }
    ]
  },
  {
    "title": "11. Microservices",
    "icon": "🔗",
    "topics": [
      {
        "name": "Service Discovery",
        "file": "service-discovery",
        "subs": [
          {
            "name": "Eureka / Consul",
            "file": "eureka-consul"
          }
        ]
      },
      {
        "name": "API Gateway",
        "file": "api-gateway",
        "subs": [
          {
            "name": "Routing & Rate Limiting",
            "file": "routing-rate-limiting"
          }
        ]
      },
      {
        "name": "Circuit Breaker",
        "file": "circuit-breaker",
        "subs": [
          {
            "name": "Resilience4j",
            "file": "resilience4j"
          },
          {
            "name": "States: CLOSED → OPEN → HALF_OPEN",
            "file": "states-closed-open-half-open"
          }
        ]
      },
      {
        "name": "Service Communication",
        "file": "service-communication",
        "subs": [
          {
            "name": "REST vs gRPC",
            "file": "rest-vs-grpc"
          },
          {
            "name": "Feign Client",
            "file": "feign-client"
          }
        ]
      },
      {
        "name": "Saga Pattern",
        "file": "saga-pattern",
        "subs": [
          {
            "name": "Choreography",
            "file": "choreography"
          },
          {
            "name": "Orchestration",
            "file": "orchestration"
          }
        ]
      }
    ]
  },
  {
    "title": "12. Messaging",
    "icon": "📨",
    "topics": [
      {
        "name": "Kafka",
        "file": "kafka",
        "subs": [
          {
            "name": "Topic / Partition / Offset",
            "file": "topic-partition-offset"
          },
          {
            "name": "Producer & Consumer",
            "file": "producer-consumer"
          },
          {
            "name": "Consumer Group",
            "file": "consumer-group"
          },
          {
            "name": "Ordering Guarantees",
            "file": "ordering-guarantees"
          }
        ]
      },
      {
        "name": "RabbitMQ",
        "file": "rabbitmq",
        "subs": [
          {
            "name": "Exchange / Queue / Binding",
            "file": "exchange-queue-binding"
          },
          {
            "name": "Routing Keys",
            "file": "routing-keys"
          }
        ]
      },
      {
        "name": "Common Concepts",
        "file": "",
        "subs": [
          {
            "name": "Dead Letter Queue (DLQ)",
            "file": "dead-letter-queue-dlq"
          },
          {
            "name": "Idempotency / Deduplication",
            "file": "idempotency-deduplication"
          },
          {
            "name": "Retry Strategies",
            "file": "retry-strategies"
          },
          {
            "name": "At-Least-Once vs Exactly-Once",
            "file": "at-least-once-vs-exactly-once"
          }
        ]
      }
    ]
  },
  {
    "title": "13. System Design",
    "icon": "🏗️",
    "topics": [
      {
        "name": "Scalability",
        "file": "scalability",
        "subs": [
          {
            "name": "Horizontal vs Vertical",
            "file": "horizontal-vs-vertical"
          },
          {
            "name": "Stateless Services",
            "file": "stateless-services"
          }
        ]
      },
      {
        "name": "Load Balancing",
        "file": "load-balancing",
        "subs": [
          {
            "name": "Algorithms",
            "file": "algorithms"
          },
          {
            "name": "Consistent Hashing",
            "file": "consistent-hashing"
          }
        ]
      },
      {
        "name": "Caching",
        "file": "caching",
        "subs": [
          {
            "name": "Cache-Aside",
            "file": "cache-aside"
          },
          {
            "name": "Write-Through / Write-Behind",
            "file": "write-through-write-behind"
          },
          {
            "name": "Eviction Policies",
            "file": "eviction-policies"
          }
        ]
      },
      {
        "name": "Database Scaling",
        "file": "database-scaling",
        "subs": [
          {
            "name": "Read Replica",
            "file": "read-replica"
          },
          {
            "name": "Sharding",
            "file": "sharding"
          },
          {
            "name": "CQRS",
            "file": "cqrs"
          }
        ]
      },
      {
        "name": "Distributed Lock",
        "file": "distributed-lock",
        "subs": [
          {
            "name": "Redis SETNX / Redlock",
            "file": "redis-setnx-redlock"
          }
        ]
      },
      {
        "name": "Rate Limiting",
        "file": "rate-limiting",
        "subs": [
          {
            "name": "Token Bucket",
            "file": "token-bucket"
          },
          {
            "name": "Sliding Window",
            "file": "sliding-window"
          }
        ]
      },
      {
        "name": "CAP Theorem",
        "file": "cap-theorem",
        "subs": []
      },
      {
        "name": "Consistency Patterns",
        "file": "consistency-patterns",
        "subs": [
          {
            "name": "Eventual Consistency",
            "file": "eventual-consistency"
          },
          {
            "name": "Strong Consistency",
            "file": "strong-consistency"
          }
        ]
      },
      {
        "name": "High Concurrency",
        "file": "high-concurrency",
        "subs": [
          {
            "name": "Sizing Thread Pool",
            "file": "sizing-thread-pool"
          },
          {
            "name": "Tuning Connection Pool",
            "file": "tuning-connection-pool"
          },
          {
            "name": "Bulkhead & Isolation",
            "file": "bulkhead-isolation"
          },
          {
            "name": "Capacity Planning",
            "file": "capacity-planning"
          }
        ]
      },
      {
        "name": "Resilience Patterns",
        "file": "circuit-breaker",
        "subs": [
          {
            "name": "Circuit Breaker",
            "file": "circuit-breaker"
          },
          {
            "name": "Retry & Backoff",
            "file": "retry-backoff"
          },
          {
            "name": "Bulkhead",
            "file": "bulkhead"
          },
          {
            "name": "Fallback & Graceful Degradation",
            "file": "fallback-degradation"
          }
        ]
      },
      {
        "name": "Data Patterns",
        "file": "event-sourcing",
        "subs": [
          {
            "name": "Event Sourcing",
            "file": "event-sourcing"
          },
          {
            "name": "Saga Pattern",
            "file": "saga-pattern"
          },
          {
            "name": "Outbox Pattern",
            "file": "outbox-pattern"
          }
        ]
      }
    ]
  },
  {
    "title": "14. Testing",
    "icon": "🧪",
    "topics": [
      {
        "name": "Unit Test",
        "file": "unit-test",
        "subs": [
          {
            "name": "JUnit 5 Annotations",
            "file": "junit-5-annotations"
          },
          {
            "name": "Parameterized Tests",
            "file": "parameterized-tests"
          }
        ]
      },
      {
        "name": "Mocking",
        "file": "mocking",
        "subs": [
          {
            "name": "Mockito (Mock / Spy / Captor)",
            "file": "mockito-mock-spy-captor"
          },
          {
            "name": "When to Mock",
            "file": "when-to-mock"
          }
        ]
      },
      {
        "name": "Integration Test",
        "file": "integration-test",
        "subs": [
          {
            "name": "@SpringBootTest",
            "file": "springboottest"
          },
          {
            "name": "TestContainers",
            "file": "testcontainers"
          }
        ]
      },
      {
        "name": "Contract Testing",
        "file": "contract-testing",
        "subs": [
          {
            "name": "Pact",
            "file": "pact"
          }
        ]
      },
      {
        "name": "Performance Testing",
        "file": "performance-testing",
        "subs": [
          {
            "name": "JMeter / Gatling / k6",
            "file": "jmeter-gatling-k6"
          }
        ]
      }
    ]
  },
  {
    "title": "15. Cloud & DevOps",
    "icon": "☁️",
    "topics": [
      {
        "name": "Docker",
        "file": "docker",
        "subs": [
          {
            "name": "Image / Container / Layer",
            "file": "image-container-layer"
          },
          {
            "name": "Dockerfile Best Practices",
            "file": "dockerfile-best-practices"
          },
          {
            "name": "Networking & Volumes",
            "file": "networking-volumes"
          }
        ]
      },
      {
        "name": "Kubernetes",
        "file": "kubernetes",
        "subs": [
          {
            "name": "Pod / Deployment / Service",
            "file": "pod-deployment-service"
          },
          {
            "name": "ConfigMap & Secret",
            "file": "configmap-secret"
          },
          {
            "name": "HPA & Rolling Update",
            "file": "hpa-rolling-update"
          },
          {
            "name": "EKS & AWS Integration",
            "file": "eks-aws-integration"
          }
        ]
      },
      {
        "name": "CI/CD",
        "file": "ci-cd",
        "subs": [
          {
            "name": "Pipeline Stages",
            "file": "pipeline-stages"
          },
          {
            "name": "Blue-Green & Canary Deploy",
            "file": "blue-green-canary-deploy"
          }
        ]
      },
      {
        "name": "Monitoring",
        "file": "monitoring",
        "subs": [
          {
            "name": "Prometheus & Grafana",
            "file": "prometheus-grafana"
          },
          {
            "name": "Distributed Tracing",
            "file": "distributed-tracing"
          },
          {
            "name": "Structured Logging",
            "file": "structured-logging"
          }
        ]
      },
      {
        "name": "Terraform",
        "file": "terraform-basics",
        "subs": [
          {
            "name": "Basics & HCL Syntax",
            "file": "terraform-basics"
          },
          {
            "name": "State Management",
            "file": "terraform-state"
          },
          {
            "name": "Modules",
            "file": "terraform-modules"
          },
          {
            "name": "Workflow & Atlantis",
            "file": "terraform-workflow-atlantis"
          }
        ]
      }
    ]
  },
  {
    "title": "16. Linux & Deployment",
    "icon": "🐧",
    "topics": [
      {
        "name": "File & Process",
        "file": "file-process",
        "subs": []
      },
      {
        "name": "Network & Logs",
        "file": "network-logs",
        "subs": []
      },
      {
        "name": "Service Deployment",
        "file": "service-deployment",
        "subs": []
      }
    ]
  },
  {
    "title": "17. AI & Agents",
    "icon": "🤖",
    "topics": [
      {
        "name": "AI Agent Fundamentals",
        "file": "agentic-loop",
        "subs": [
          {
            "name": "Agentic Loop & ReAct",
            "file": "agentic-loop"
          },
          {
            "name": "Function Calling & Tool Use",
            "file": "function-calling"
          },
          {
            "name": "Agent Memory",
            "file": "agent-memory"
          }
        ]
      },
      {
        "name": "MCP & Protocols",
        "file": "mcp-overview",
        "subs": [
          {
            "name": "MCP Overview",
            "file": "mcp-overview"
          },
          {
            "name": "Build MCP Server",
            "file": "mcp-server-build"
          },
          {
            "name": "A2A Protocol",
            "file": "a2a-protocol"
          }
        ]
      },
      {
        "name": "Frameworks",
        "file": "google-adk",
        "subs": [
          {
            "name": "Google ADK",
            "file": "google-adk"
          },
          {
            "name": "LangGraph",
            "file": "langgraph"
          }
        ]
      },
      {
        "name": "Production AI",
        "file": "rag-pattern",
        "subs": [
          {
            "name": "RAG Pattern",
            "file": "rag-pattern"
          },
          {
            "name": "Prompt Engineering",
            "file": "prompt-engineering"
          },
          {
            "name": "LLM Gateway (LiteLLM)",
            "file": "llm-gateway"
          },
          {
            "name": "AI Observability",
            "file": "ai-observability"
          }
        ]
      }
    ]
  },
  {
    "title": "18. API & Communication",
    "icon": "🔌",
    "topics": [
      {
        "name": "REST & HTTP",
        "file": "restful-design",
        "subs": [
          {
            "name": "RESTful Design",
            "file": "restful-design"
          },
          {
            "name": "API Best Practices",
            "file": "api-best-practices"
          },
          {
            "name": "OpenAPI & Swagger",
            "file": "openapi-swagger"
          }
        ]
      },
      {
        "name": "gRPC",
        "file": "grpc-deep",
        "subs": [
          {
            "name": "gRPC Deep Dive",
            "file": "grpc-deep"
          }
        ]
      },
      {
        "name": "GraphQL",
        "file": "graphql",
        "subs": [
          {
            "name": "GraphQL",
            "file": "graphql"
          }
        ]
      },
      {
        "name": "Real-time",
        "file": "websocket-sse",
        "subs": [
          {
            "name": "WebSocket & SSE",
            "file": "websocket-sse"
          }
        ]
      }
    ]
  },
  {
    "title": "19. Observability",
    "icon": "🔭",
    "topics": [
      {
        "name": "Logging",
        "file": "structured-logging",
        "subs": [
          {
            "name": "Structured Logging",
            "file": "structured-logging"
          }
        ]
      },
      {
        "name": "Metrics",
        "file": "metrics-prometheus",
        "subs": [
          {
            "name": "Metrics & Prometheus",
            "file": "metrics-prometheus"
          }
        ]
      },
      {
        "name": "Tracing",
        "file": "distributed-tracing",
        "subs": [
          {
            "name": "Distributed Tracing",
            "file": "distributed-tracing"
          }
        ]
      }
    ]
  },
  {
    "title": "20. Security",
    "icon": "🔒",
    "topics": [
      {
        "name": "Auth & Identity",
        "file": "oauth2-oidc",
        "subs": [
          {
            "name": "OAuth2 & OIDC",
            "file": "oauth2-oidc"
          },
          {
            "name": "JWT Security",
            "file": "jwt-security"
          }
        ]
      },
      {
        "name": "OWASP",
        "file": "owasp-top10",
        "subs": [
          {
            "name": "OWASP Top 10",
            "file": "owasp-top10"
          }
        ]
      }
    ]
  },
  {
    "title": "21. .NET",
    "icon": "💜",
    "topics": [
      {
        "name": "C# Cơ Bản",
        "file": "csharp-vs-java",
        "subs": []
      },
      {
        "name": "ASP.NET Core",
        "file": "aspnet-core",
        "subs": []
      },
      {
        "name": "Entity Framework Core",
        "file": "ef-core",
        "subs": []
      },
      {
        "name": ".NET Async & Task",
        "file": "dotnet-async",
        "subs": []
      },
      {
        "name": "DI & Middleware",
        "file": "dotnet-di-middleware",
        "subs": []
      },
      {
        "name": "Concurrency",
        "file": "dotnet-concurrency",
        "subs": []
      },
      {
        "name": "Memory & GC",
        "file": "dotnet-memory-gc",
        "subs": []
      },
      {
        "name": "C# Nâng Cao",
        "file": "csharp-advanced",
        "subs": []
      },
      {
        "name": "Testing (xUnit & Moq)",
        "file": "dotnet-testing",
        "subs": []
      },
      {
        "name": "Security (JWT & Policy)",
        "file": "aspnet-security",
        "subs": []
      }
    ]
  },
  {
    "title": "22. Ruby",
    "icon": "💎",
    "topics": [
      {
        "name": "Ruby Cơ Bản",
        "file": "ruby-basics",
        "subs": []
      },
      {
        "name": "OOP & Modules",
        "file": "ruby-oop",
        "subs": []
      },
      {
        "name": "Ruby vs Java",
        "file": "ruby-vs-java",
        "subs": []
      },
      {
        "name": "Rails Cơ Bản",
        "file": "ruby-rails",
        "subs": []
      },
      {
        "name": "Concurrency & GIL",
        "file": "ruby-concurrency",
        "subs": []
      },
      {
        "name": "Metaprogramming",
        "file": "ruby-metaprogramming",
        "subs": []
      },
      {
        "name": "Testing (RSpec & FactoryBot)",
        "file": "ruby-testing",
        "subs": []
      },
      {
        "name": "Rails Nâng Cao",
        "file": "rails-advanced",
        "subs": []
      },
      {
        "name": "Ruby Internals",
        "file": "ruby-internals",
        "subs": []
      }
    ]
  }
];;
